version: 0.2
sparkVersion: 2.4.5
image: metorikku/k8s-spark-operator
jar: file:///target/metorikku.jar
mainClass: com.yotpo.metorikku.Metorikku
fileDependencies: []
arguments:
  - -c
  - "/opt/spark/work-dir/examples/movies.yaml"
volumes:
  - name: "examples"
    hostPath:
      path: "/Users/giladweinbach/Development/yotpo-workspace/metorikku/examples"
      type: Directory
  - name: "target"
    hostPath:
      path: "/Users/giladweinbach/Development/yotpo-workspace/metorikku/target/scala-2.11"
      type: Directory
driver:
  cores: 1
  coreLimit: 1
  memory: "512m"
  mounts:
    examples: "/opt/spark/work-dir/examples"
    target: /target
executor:
  cores: 1
  coreLimit: 1
  instances: 1
  memory: "512m"
  mounts:
    examples: "/opt/spark/work-dir/examples/"