useAtlas:
  atlas.kafka.zookeeper.connect: ${ATLAS_ZOOKEEPER_CONNECT}
  atlas.kafka.bootstrap.servers: ${ATLAS_BOOTSTRAP_SERVERS}
  spark.extraListeners: com.hortonworks.spark.atlas.SparkAtlasEventTracker
  spark.sql.queryExecutionListeners: com.hortonworks.spark.atlas.SparkAtlasEventTracker
  spark.sql.streaming.streamingQueryListeners: com.hortonworks.spark.atlas.SparkAtlasStreamingQueryEventTracker